### ISSUE TITLE
GH Auth failing for Daniel S

### ISSUE THREAD

**Issue by brianleroux** [smallwins/bugbot#52]
(Rad domain btw dude)

Issue is failing Github auth lookup directs to re-auth but that itself fails. 

Couple of requests:

- Can you try removing from Slack and re-adding? (And LMK how that goes.) 
- Also what was the Github name you had last associated?

**Comment by selfagency** [comment]
- removed and re-added and no es bueno 
- the name is nylonmedia

![screenshot 2016-03-02 18 01 52](https://cloud.githubusercontent.com/assets/2541728/13478833/fa71db5e-e0a0-11e5-993c-efcd728dfced.png)

**Comment by brianleroux** [comment]
k, on it --- thx for the patience @selfagency 👊🏽

**Comment by brianleroux** [comment]
Really odd, it def reports that you have added but there's no token in the db for your team. Hmm. 

Could you try this:

1. Hit remove app on the integration page
2. Add it back hitting the add to slack here http://smallwins.today/bugbot
3. Run `/bugbot repos` to get the github message
4. [Authorize Github here](https://github.com/login/oauth/authorize?client_id=acaf9b8e29df291501ab&scope=user,repo&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiVTAzTTNVNDhYIiwidGVhbV9pZCI6IlQwM001QTQyTCIsImlhdCI6MTQ1Njk2MDI3N30.xWSAl2Hs9IyXIga44kOK-VYD7vTPxGI7ZPGYNEARceE)

I'll watch our logs and see if I see anything freaky.
then try authing

**Comment by selfagency** [comment]
that's what i've done 4 times already

**Comment by brianleroux** [comment]
Yea, sorry I know this is the very definition of insanity. (But this time I removed your account from our DB so it would be an actually really fresh attempt)

**Comment by selfagency** [comment]
ok proceeding

**Comment by selfagency** [comment]
same deal

**Comment by selfagency** [comment]
should i try removing my authorization within github?

**Comment by brianleroux** [comment]
boo. gimme a few / going to sift through the logs :mag:

**Comment by brianleroux** [comment]
(yea give that a try and a full cycle on the add/remove from slack… :beers: on me when we figure this out!)

**Comment by selfagency** [comment]
that did it! removing the oauth inside of github.

**Comment by selfagency** [comment]
but what does that mean for my colleagues who added it? do they all have to delete and reauth now?

**Comment by brianleroux** [comment]
afraid so :disappointed: 

not entirely sure wtf happened there but the account was there but the auth tokens not 

(btw if you happen to be located in SF or Vancouver or Chicago I will be in those places in the coming months and totally good on my word for that :beer:)

**Comment by selfagency** [comment]
i appreciate it-- i'm an upstate nyer however. um, please do keep an eye out for this issue resurfacing b/c nothing happened on our end to alter our settings.

**Comment by brianleroux** [comment]
:+1: 

I have a suspect but I do not like it. I upgraded Node today. :grimacing: (If its ok w/ you I'll close this issue.)

**Comment by selfagency** [comment]
yessir

**Comment by brianleroux** [comment]
:pray:
